[env:esp32c3]
platform = espressif32
board = esp32-c3-devkitm-1
board_build.mcu = esp32c3
framework = arduino
monitor_speed = 115200

debug_tool = esp-builtin
upload_protocol = esptool

board_build.f_cpu = 80000000L
board_build.filesystem = littlefs
board_build.data_dir = data

build_flags = 
  -DARDUINO_USB_CDC_ON_BOOT=1
  -DARDUINO_USB_MODE=1
  -DCORE_DEBUG_LEVEL=2



monitor_filters = 
    esp32_exception_decoder
    time      ; Add timestamp with milliseconds for each new line
    direct    ; Use direct for better performance with some adapters

monitor_dtr = 1
monitor_rts = 1
monitor_port = COM5

lib_deps = 
	kitesurfer1404/WS2812FX@^1.4.4
	adafruit/Adafruit NeoPixel@^1.12.3
	igorantolic/Ai Esp32 Rotary Encoder @ ^1.7
	bblanchon/ArduinoJson@^6.19.4
	mathieucarbou/AsyncTCP @ ^3.2.4
	mathieucarbou/ESPAsyncWebServer @ ^3.1.5
